name: Publish to container registry

on:
  push:
    tags:
      - "v*.*.*" # Only publish if there is a git tag that is a version number

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check version in package.json matches git tag
        run: |
          PKG_VERSION=$(jq -r '.version' package.json)
          TAG_VERSION=${GITHUB_REF_NAME#v}

          echo "Package.json version: $PKG_VERSION"
          echo "Git tag version:      $TAG_VERSION"

          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "Version mismatch! Aborting..."
            exit 1
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
